---
# some sections error'd with 2 spaces indentation, keep 4!
# dev_addr: '127.0.0.1:8000'  # address used when running mkdocs serve
site_name: Public Notes
site_url: https://SebastianErfort.github.io/pub_notes
site_author: Sebastian Erfort
site_dir: public # changed value to default for GitLab Pages
copyright: Sebastian Erfort
repo_name: git.lwp.rug.nl
repo_url: https://SebastianErfort.github.io/pub_notes
edit_uri_template: '-/wikis/{path_noext!q}/edit'  # doesn't work yet
plugins:
    - search:
        lang: en
    - tags  # see https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#setting-up-tags
    - exclude:  # see https://github.com/apenwarr/mkdocs-exclude
        glob:
            - ".obsidian/*"
            - ".git"
        regex:
            # avoid duplicate pages for sym-linked index/home pages
            # - "wiki/(chris|heiko|jacob|jurjen|remco|sebastian)/[Hh]ome.md"
    - ezlinks  # see https://pypi.org/project/mkdocs-ezlinked-plugin/
    - obsidian-support  # see https://github.com/ndy2/mkdocs-obsidian-support-plugin
theme:
  name: material
  # logo: assets/logo.png  # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  palette:
    # custom primary color set through css import extra_css
    # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors
    primary: custom
  features:
    - content.code.copy  # see https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - navigation.tabs
    - toc.follow
extra_css:
  - stylesheets/extra.css
  - stylesheets/gitlab.css
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - admonition
    - pymdownx.tasklist
    # use 2 spaces indentation (spec. for many MD flavours), sane vertical spacing
    - mdx_truly_sane_lists:
        nested_indent: 4  # change indentation threshold - can't have both 2 and 4
    - footnotes
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - toc:
        permalink: "🔗"  # Generate permanent links at the end of each header
        baselevel: 2
        # marker: '[[_TOC_]]'  # no effect, material documentation doesn't mention this keyword
        # permalink_title:  # can maybe used with variable/template to get heading text instead of icon?
    # - wikilinks  # See https://python-markdown.github.io/extensions/wikilinks/
    # Instead using ezlinked
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
        linenums: false

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

...
